# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxhwr4AyVJAogOh7qcE-DZp3FXryrLZb
"""

import math
import matplotlib.pyplot as plt

def function(x):
    return x**2 + 4*x

def diff(x):
    return 2*x + 4

alpha = 0.1
x = float(input("Enter value of x:"))

# Lists to store values for plotting
x_values = []
function_values = []

while abs(diff(x)) >= 0.001:
    x_values.append(x)
    function_values.append(function(x))
    x = x - alpha * diff(x)
    print(f"Value of x: {x}")

# Add the final value for plotting
x_values.append(x)
function_values.append(function(x))
print(f"Final value of x: {x}")

# Plotting the graph
plt.plot(x_values, function_values, marker='o')
plt.xlabel('x')
plt.ylabel('function(x)')
plt.title('Gradient Descent Optimization')
plt.grid(True)
plt.show()